#  ------------------------------------------------------------
#  |                      RealChat plugin                     |
#  |                                                          |
#  |                     Author : huda0209                    |
#  |                       Depend : Vault                     |
#  |     GitHub : https://github.com/huda0209/OfflinePay      |
#  |                     ran by paper 1.13                    |
#  ------------------------------------------------------------


PluginMode: true